### ISSUE TITLE
Make graph color independent from legend and legend display configurable

### ISSUE THREAD

**Issue by camueller** [sanlike0911/node-red-contrib-ui-timelines-chart#11]
Currently the graph color can only be conifgured as part of the legend. Having a simple data set like:
```
{
  "dataItems":[
    {
      "group": "",
      "data": [
        {
          "label": "",
          "data": [
            {
              "timeRange": [
                "2021-12-18T08:00:00",
                "2021-12-18T12:00:00"
              ],
              "val": "30"
            },
            {
              "timeRange": [
                "2021-12-18T16:00:00",
                "2021-12-18T20:00:00"
              ],
              "val": "5"
            },
            {
              "timeRange": [
                "2021-12-19T12:00:00",
                "2021-12-19T13:00:00"
              ],
              "val": "15"
            }
          ]
        }
      ]
    }
  ],
  "settings": {
    "xAxis": {
      "startDateTime": "2021-12-18T00:00:00",
      "endDateTime": "2021-12-19T23:59:00"
    }
  }
}
```
with only color configured (by setting it in the legend configuration) results in this:

![image](https://user-images.githubusercontent.com/4489628/146641496-78918dae-d1d2-4114-ab0d-9548b3639088.png)

The legend is pretty useless in this case but cannot be disabled. It would be nice to habe a `settings` parameter to disable it.
However it should still be possible to configure the graph color.

**Comment by camueller** [comment]
The legend can be hidden if `topMargin: 0` which is currently hard-coded set to 60.
I created a PR in order to make `topMargin` configurable: https://github.com/sanlike0911/node-red-contrib-ui-timelines-chart/pull/13

**Comment by sanlike0911** [comment]
Thanks for the great suggestions
v0.15 has been released.

When `top Margin: 0` is set, there is a problem that hides `reset zoom`.
This issue will be resolved in the next release.
