### ISSUE TITLE
[Question] Remove dd/mm/yyyy from label

### ISSUE THREAD

**Issue by ThomasAndreini** [sanlike0911/node-red-contrib-ui-timelines-chart#15]
Hi, I'm sorry if I open an issue for a question but I didn't know where to ask it. I work on a program that uses your excellent time chart, but I only use hours and minutes, I don't need the date and I always use the date 01/01/1970, you can remove it from the labels that appear when you select the object in the time line?
I attach a screen. Thank 
![scereen](https://user-images.githubusercontent.com/17955700/148911166-68c9e26d-77f2-4665-822c-f17cf78f1380.png)
you

**Comment by sanlike0911** [comment]
Hi, Thank you for using this node-red-contrib-ui-timelines-chart.

You can't change the tooltip format from Node-RED yet, but the Graph Library has the ability to change the tooltip format.
I have a suggestion. This can be achieved by changing and building the latest program of GITHUB. Please change the "timeFormat" of this "ui_timelines_chart.ts".

[ui_timelines_chart.ts]
Please change here.  -> .timeFormat('%H:%M')
https://github.com/sanlike0911/node-red-contrib-ui-timelines-chart/blob/be5710508d636a07778b0c31f43ae3dfc5d9c051/src/nodes/ui_timelines_chart.ts#L470

![image](https://user-images.githubusercontent.com/15191760/149041722-bc1f3d9a-6288-4331-9b3c-b5a516b6f6ba.png)

We will add this feature in the next update.

**Comment by ThomasAndreini** [comment]
Thank you very much for your availability, I am in no hurry, I am calmly waiting for it to be integrated into the new version.  Congratulations for the node, it's done very well
