### ISSUE TITLE
version 0.1.7 installation give error

### ISSUE THREAD

**Issue by ThomasAndreini** [sanlike0911/node-red-contrib-ui-timelines-chart#16]
Hi, when I try to install 0.1.7 (upgrade or new install) it install node but when I reload node red I give a general error about it, go in the manage palette I found this:

![error](https://user-images.githubusercontent.com/17955700/149744357-b07f7115-80a5-4593-afd9-7f8a528ebaab.png)

**Comment by sanlike0911** [comment]
Hi, Thank you for using this node-red-contrib-ui-timelines-chart.

I forgot to register nodes files.
That I have released v0.1.8, please update the node-red-contrib-ui-timelines-chart.

**Comment by ThomasAndreini** [comment]
Now work thank you so much
