### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bbartling** [sanlike0911/node-red-contrib-ui-timelines-chart#5]
Hi,

I am a node red newbie, this module seems interesting.

This may sound like a real odd question, could I ever use this as a "fault detection diagnostics checker?"

For example I work in the HVAC industry where I collect a lot sensor data and people create fault detection diagnostics if a sensor on the heating/cooling system for large buildings/hospitals is reading erroneous values. Sometimes the sensor value can be related to a mechanical issue (like broken valve in a piping system is leaking hot or cold water) or the electronics has an issue.

A classic one is buildings control a lot of HVAC based on locally installed outside air temperature sensor reading, and sometimes they install the sensor where it is hit by sunlight and that causes a whole mess of issues when HVAC starts going into a summer mode but it is actually winter time. Could this node red module ever be used to detect a sensor going out of range of acceptable values, and then documenting over time on a chart how often this error happens?

Thanks for anytime in response! 
Ben

**Comment by sanlike0911** [comment]
Hi,

Thank you for using "node-red-contrib-ui-timelines-chart".
Please excuse my poor English.

>This may sound like a really odd question, could I ever use this as a "fault detection diagnostics checker?"
Yes. I think it is possible.

I'm using this Node-RED module as a "fault detection diagnostic checker" for factory machines. This may be the same as you think.

Please note that this Node-Red module can visualize the status of many devices, but you can not calculate or save data. Also, need a database to compare past data.

Sensor values are required to replace values from the range of the tolerance range (e.g. State-normal: 39 or less Degree, State-Warn: 40-69Degree, State-Err: 70 or more degree) Become. 

I hope that answers your question.
sanlike0911

**Comment by bbartling** [comment]
Thank you!
