### ISSUE TITLE
Wrong variable name in settings

### ISSUE THREAD

**Issue by sanlike0911** [sanlike0911/node-red-contrib-ui-timelines-chart#6]
msg.payload.settings.xAxis

[before]
```json
    "settings":{
        "xAxis":{
            "startDate": "<datetime>",
            "endDate": "<datetime>",
```

[after]
```json
    "settings":{
        "xAxis":{
            "startDateTime": "<datetime>",
            "endDateTime": "<datetime>",
```

**Comment by misiekmiskow** [comment]
HI
Do you have FLOW with connect database (mysql, mssql).

**Comment by sanlike0911** [comment]
Hi.

This Node-Red module can not directly connect to Database.

## Example
This is a simple sample.
1.Database Node => 2.Template Node => 3. Timelines-Chart Node

1. Database Node
Get display data.

2. Template Node
Convert to a data structure for displaying with "Timelines-Chart".

3. Timelines-chart
[IN: msg.payloda]
```json
{
    dataItems:[
        {
            group: "group1name",
            data: [
            {
                label: "label1name",
                data: [
                {
                    timeRange: [<date>, <date>],
                    val: <val: number (continuous dataScale) or string (ordinal dataScale)>
                },
                {
                    timeRange: [<date>, <date>],
                    val: <val>
                },
                (...)
                ]
            },
            {
                label: "label2name",
                data: [...]
            },
            (...)
            ],
        },
        {
            group: "group2name",
            data: [...]
        },
        (...)
    ],
    settings:{
        xAxis:{
            tickFormat: <val: string (YYYY-MM-DD HH:mm:ss)>,
            startDateTime: <date>,
            endDateTime: <date>,
            labelsFontSize: <val: number (from 0 to 64[default:16])>
            labelsColor: <val: string (from #000000 to #ffffff[default:#000000])>
        },
        yAxis:{
            labelsFontSize: <val: number (from 0 to 64[default:16])>
            labelsColor: <val: string (from #000000 to #ffffff[default:#000000])>
        },
        resetZoom:{
            labelFontSize: <val: number (from 0 to 64[default:24])>
            labelColor: <val: string (from #000000 to #ffffff[default:#000000])>
        },
        chart:{
          height: <val: number (from 1 to 255[default:60])>
          lineColors <{val: string (from #000000 to #ffffff[default:#000000]), val: string (label name)}>,
        },
        options:{
          enableAnimations: <boolean>,
          enableDateMarker: <boolean>
        }
    }
}
```

**Comment by misiekmiskow** [comment]
Ok
Thx

Misiek

pt., 3 wrz 2021, 16:18 użytkownik sanlike ***@***.***>
napisał:

**Comment by misiekmiskow** [comment]
how implement this payload
can you help me.
I not informatic

my msg.payload from database

[{"id":"8b74876.1f0b778","type":"inject","z":"708bb063.f7474","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[{\"start\":\"2021-09-05T11:47:08.000Z\",\"end\":\"2021-09-05T11:49:38.000Z\",\"group\":\"Stop\",\"label\":\"33\"},{\"start\":\"2021-09-05T11:41:53.000Z\",\"end\":\"2021-09-05T11:47:08.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-05T11:39:23.000Z\",\"end\":\"2021-09-05T11:41:53.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-05T11:34:08.000Z\",\"end\":\"2021-09-05T11:39:23.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-05T11:21:08.000Z\",\"end\":\"2021-09-05T11:34:08.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-05T11:20:54.000Z\",\"end\":\"2021-09-05T11:21:08.000Z\",\"group\":\"Cwu\",\"label\":\"\"},{\"start\":\"2021-09-05T11:13:53.000Z\",\"end\":\"2021-09-05T11:20:54.000Z\",\"group\":\"Cwu\",\"label\":\"66\"},{\"start\":\"2021-09-05T11:12:23.000Z\",\"end\":\"2021-09-05T11:13:53.000Z\",\"group\":\"Cwu\",\"label\":\"100\"},{\"start\":\"2021-09-05T11:12:09.000Z\",\"end\":\"2021-09-05T11:12:23.000Z\",\"group\":\"Cwu\",\"label\":\"\"},{\"start\":\"2021-09-05T11:11:53.000Z\",\"end\":\"2021-09-05T11:12:09.000Z\",\"group\":\"Cwu\",\"label\":\"100\"},{\"start\":\"2021-09-05T11:06:53.000Z\",\"end\":\"2021-09-05T11:11:53.000Z\",\"group\":\"Cwu\",\"label\":\"66\"},{\"start\":\"2021-09-05T11:01:38.000Z\",\"end\":\"2021-09-05T11:06:53.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T23:38:57.000Z\",\"end\":\"2021-09-05T11:01:38.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T23:36:42.000Z\",\"end\":\"2021-09-04T23:38:57.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T23:31:27.000Z\",\"end\":\"2021-09-04T23:36:42.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T23:28:42.000Z\",\"end\":\"2021-09-04T23:31:27.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T23:23:27.000Z\",\"end\":\"2021-09-04T23:28:42.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T23:11:12.000Z\",\"end\":\"2021-09-04T23:23:27.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T23:06:42.000Z\",\"end\":\"2021-09-04T23:11:12.000Z\",\"group\":\"Cwu\",\"label\":\"66\"},{\"start\":\"2021-09-04T23:01:42.000Z\",\"end\":\"2021-09-04T23:06:42.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T15:50:11.000Z\",\"end\":\"2021-09-04T23:01:42.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T15:47:41.000Z\",\"end\":\"2021-09-04T15:50:11.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T15:42:26.000Z\",\"end\":\"2021-09-04T15:47:41.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T15:39:41.000Z\",\"end\":\"2021-09-04T15:42:26.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T15:34:26.000Z\",\"end\":\"2021-09-04T15:39:41.000Z\",\"group\":\"Stop\",\"label\":\"0\"},{\"start\":\"2021-09-04T15:24:56.000Z\",\"end\":\"2021-09-04T15:34:26.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T15:24:42.000Z\",\"end\":\"2021-09-04T15:24:56.000Z\",\"group\":\"Cwu\",\"label\":\"\"},{\"start\":\"2021-09-04T15:23:11.000Z\",\"end\":\"2021-09-04T15:24:42.000Z\",\"group\":\"Cwu\",\"label\":\"33\"},{\"start\":\"2021-09-04T15:22:56.000Z\",\"end\":\"2021-09-04T15:23:11.000Z\",\"group\":\"\",\"label\":\"\"},{\"start\":\"2021-09-04T15:21:56.000Z\",\"end\":\"2021-09-04T15:22:56.000Z\",\"group\":\"\",\"label\":\"33\"}]","payloadType":"json","x":200,"y":480,"wires":[["98b12ba5.d04b08"]]}]


pt., 3 wrz 2021 o 16:42 sanlike ***@***.***> napisał(a):

**Comment by sanlike0911** [comment]
There is an error in "msg.payload".

Please correct it referring to the following.

[msg.payload]
```json
{
   "dataItems":[
      {
         "group":"Stop",
         "data":[
            {
               "label":"label-stop",
               "data":[
                  {
                     "timeRange":[
                        "2021-09-05T11:47:08.000Z",
                        "2021-09-05T11:49:38.000Z"
                     ],
                     "val":"33"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:41:53.000Z",
                        "2021-09-05T11:47:08.000Z"
                     ],
                     "val":"0"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:34:08.000Z",
                        "2021-09-05T11:39:23.000Z"
                     ],
                     "val":"0"
                  },
                  {
                     "timeRange":[
                        "2021-09-04T23:38:57.000Z",
                        "2021-09-05T11:01:38.000Z"
                     ],
                     "val":"0"
                  },
                  {
                     "timeRange":[
                        "2021-09-04T23:31:27.000Z",
                        "2021-09-04T23:36:42.000Z"
                     ],
                     "val":"0"
                  },
                  {
                     "timeRange":[
                        "2021-09-04T23:23:27.000Z",
                        "2021-09-04T23:28:42.000Z"
                     ],
                     "val":"0"
                  },
                  {
                     "timeRange":[
                        "2021-09-04T15:50:11.000Z",
                        "2021-09-04T23:01:42.000Z"
                     ],
                     "val":"0"
                  }
               ]
            }
         ]
      },
      {
         "group":"Cwu",
         "data":[
            {
               "label":"label-cwu",
               "data":[
                  {
                     "timeRange":[
                        "2021-09-05T11:39:23.000Z",
                        "2021-09-05T11:41:53.000Z"
                     ],
                     "val":"33"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:21:08.000Z",
                        "2021-09-05T11:34:08.000Z"
                     ],
                     "val":"33"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:20:54.000Z",
                        "2021-09-05T11:21:08.000Z"
                     ],
                     "val":""
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:13:53.000Z",
                        "2021-09-05T11:20:54.000Z"
                     ],
                     "val":"66"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:12:23.000Z",
                        "2021-09-05T11:13:53.000Z"
                     ],
                     "val":"100"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:12:09.000Z",
                        "2021-09-05T11:12:23.000Z"
                     ],
                     "val":""
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:11:53.000Z",
                        "2021-09-05T11:12:09.000Z"
                     ],
                     "val":"100"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:06:53.000Z",
                        "2021-09-05T11:11:53.000Z"
                     ],
                     "val":"66"
                  },
                  {
                     "timeRange":[
                        "2021-09-05T11:01:38.000Z",
                        "2021-09-05T11:06:53.000Z"
                     ],
                     "val":"33"
                  }
               ]
            }
         ]
      }
   ]
}
```

[sisplay example]
![image](https://user-images.githubusercontent.com/15191760/132143986-a603ceb4-d8c8-44fc-9a51-b5c5b9552b5c.png)

**Comment by misiekmiskow** [comment]
I have RASPBERRY PI 3
version 0,1,1 - super - all OK
version 0,1,2 - :(

   - Error:
   /home/pi/.node-red/node_modules/node-red-contrib-ui-timelines-chart/nodes/ui_timelines_chart.html
   does not exist
   - What problem ???


pon., 6 wrz 2021 o 01:21 sanlike ***@***.***> napisał(a):

**Comment by sanlike0911** [comment]
Hi

Thank you for reporting the problem.
I going to check this issue.

 >I have RASPBERRY PI 3
 >version 0,1,1 - super - all OK 
 >version 0,1,2 - :(

sanlike0911

**Comment by misiekmiskow** [comment]
your plugin it's ok - work
after instal your plugin 0,1,3 - not work tittle bar and menu of the site
and name website Node-Red + chines string  [image: image.png]

śr., 8 wrz 2021 o 16:16 sanlike ***@***.***> napisał(a):
